# Generated by Django 5.1.7 on 2025-03-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("typename", models.CharField(max_length=50, verbose_name="类别名称")),
            ],
            options={
                "verbose_name": "博客类别管理",
                "verbose_name_plural": "博客类别管理",
            },
        ),
    ]
