# Generated by Django 5.1.7 on 2025-04-03 02:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogtype_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="博客标题")),
                ("content", models.CharField(max_length=1000, verbose_name="博客内容")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="blog/", verbose_name="文章图片"
                    ),
                ),
                ("reads", models.IntegerField(default=0, verbose_name="阅读人数")),
                ("abstract", models.CharField(max_length=300, verbose_name="博客摘要")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 4, 3, 2, 19, 32, 744970, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户（博客作者）",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogtype",
                        verbose_name="博客类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客帖子管理",
                "verbose_name_plural": "博客帖子管理",
            },
        ),
    ]
