# Generated by Django 5.1.7 on 2025-04-11 09:56

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 11, 9, 56, 43, 612428, tzinfo=datetime.timezone.utc
                ),
                verbose_name="创建时间",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=60, verbose_name="评论用户")),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="评论创建时间"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="博客作者",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blog",
                        verbose_name="评论所属博客",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客评论管理",
                "verbose_name_plural": "博客评论管理",
            },
        ),
    ]
