# Generated by Django 5.1.7 on 2025-04-12 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_create_time_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogtype",
            name="user",
        ),
        migrations.AlterField(
            model_name="blog",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 12, 10, 42, 15, 291433, tzinfo=datetime.timezone.utc
                ),
                verbose_name="创建时间",
            ),
        ),
    ]
